### ISSUE TITLE
is the project still working /active ?

### ISSUE THREAD

**Issue by gurugeek** [Swift-Squirrel/Squirrel#38]
cannot load the squirrel.codes website or run the example.

**Comment by LeoNavel** [comment]
Hi, webpage is accessible at https://squirrel-develop.herokuapp.com/docs/Getting-Started/ but the repository is no longer active :/ this web page is using Squirrel framework and it seems to run without problem. Are getting any errors? If there is anything you are interested in just ask and I will try my best to help you :)

**Comment by gurugeek** [comment]
thanks for letting me know !
it seems that one of the dependencies repositories is not working 
"error: Failed to clone https://github.com/tris-foundation/test.git:"

Fetching https://github.com/Swift-Squirrel/Squirrel.git
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/SwiftyBeaver/SwiftyBeaver.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/IBM-Swift/BlueSocket
Fetching https://github.com/vapor/crypto.git
Fetching https://github.com/tris-foundation/test.git
Fetching https://github.com/Swift-Squirrel/SquirrelJSON.git
Fetching https://github.com/Swift-Squirrel/Squirrel-Core.git
error: Failed to clone https://github.com/tris-foundation/test.git:
    Cloning into bare repository '/Users/gurugeek/swift/squirrelpress/.build/repositories/test-0c84c340'...

**Comment by LeoNavel** [comment]
This dependency is just for testing but I it seems like most of dependencies are broken :/ take a look at [vapor](https://docs.vapor.codes/3.0/). It has bigger community and their work is really nice :)

**Comment by gurugeek** [comment]
allright thanks
